name: build
on: [pull_request, push]

jobs:
  build:
      runs-on: ubuntu-20.04
      steps:
          - name: checkout repository
            uses: actions/checkout@v2
          - name: validate gradle wrapper
            uses: gradle/wrapper-validation-action@v1
          - name: setup jdk 16
            uses: actions/setup-java@v2
            with:
                distribution: adopt
                java-version: 16
          - name: make gradle wrapper executable
            if: ${{ runner.os != 'Windows' }}
            run: chmod +x ./gradlew
          - name: build
            run: ./gradlew build
